global:
  scrape_interval: 5s
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090

- job_name : app_python
  static_configs:
  - targets:
    - 34.204.197.239:5000

- job_name: node-interno
  static_configs:
  - targets: 
    - 172.31.91.230:9100

- job_name: cadvisor
  static_configs:
  - targets:
    - 172.31.91.230:8081